name: Run notebooks

on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * *"

jobs:
  run-notebooks:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']
        nb: [
          {title: quickstart, name: TorchIO_tutorial},
          {title: "brain parcellation", name: Brain_parcellation_with_TorchIO_and_HighRes3DNet},
          {title: transforms, name: Data_preprocessing_and_augmentation_using_TorchIO_a_tutorial},
          {title: frameworks, name: TorchIO_MONAI_PyTorch_Lightning},
        ]
        exclude:
          - os: macos-latest
            python-version: '3.7'
          - os: macos-latest
            python-version: '3.8'
          - os: macos-latest
            python-version: '3.9'
          - os: windows-latest
            python-version: '3.7'
          - os: windows-latest
            python-version: '3.8'
          - os: windows-latest
            python-version: '3.9'
      fail-fast: false

    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}

    steps:
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          pip install ipython ipykernel papermill
          ipython kernel install --name "python3" --user

      - name: Run ${{ matrix.nb.title }} notebook
        run: papermill notebooks/${{ matrix.nb.name }}.ipynb /tmp/${{ matrix.nb.name }}.ipynb
