name: Run notebooks

on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * *"

jobs:
  run-notebooks:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}

    steps:
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          pip install ipython ipykernel papermill
          ipython kernel install --name "python3" --user

      - name: Run quickstart notebook
        run: papermill notebooks/TorchIO_tutorial.ipynb /tmp/tt.ipynb

      - name: Run brain parcellation notebook
        run: papermill notebooks/Brain_parcellation_with_TorchIO_and_HighRes3DNet.ipynb /tmp/bp.ipynb

      - name: Run transforms notebook
        run: papermill notebooks/Data_preprocessing_and_augmentation_using_TorchIO_a_tutorial.ipynb /tmp/dpat.ipynb

      - name: Run frameworks notebook
        run: papermill notebooks/TorchIO_MONAI_PyTorch_Lightning.ipynb /tmp/tmptl.ipynb
